# Generated by Django 3.1.1 on 2020-11-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_account_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acount_name', models.CharField(default='Job Seeker', max_length=60)),
                ('Account_type', models.CharField(default='js', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('user_mobile', models.IntegerField(blank=True, null=True)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_marital_status', models.CharField(max_length=5)),
                ('user_DOB', models.DateField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user_account_type')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('district', models.TextField()),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('zip_code', models.SmallIntegerField()),
                ('p_o_box', models.SmallIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
