# Generated by Django 3.1.1 on 2020-11-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201111_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='endorsments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='roles_level_id',
            new_name='roles_level',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='user_id',
            new_name='user',
        ),
    ]
