# Generated by Django 3.1.1 on 2020-11-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201112_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='user_nationality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_marital_status',
            field=models.CharField(max_length=50),
        ),
    ]
