# Generated by Django 3.1.1 on 2020-11-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201112_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='visa_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.visa_type'),
        ),
    ]
