# Generated by Django 3.1.1 on 2020-11-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20201115_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='mationality',
            new_name='nationality',
        ),
    ]
