# Generated by Django 3.1.1 on 2020-11-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_user_profile_marriatal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_name', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('date_of_expire', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
