# Generated by Django 3.1.1 on 2020-11-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='visa_status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='start.visa'),
            preserve_default=False,
        ),
    ]
