# Generated by Django 3.1.1 on 2020-11-15 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_user_profile_visa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 16, 26, 44, 734534), null=True)),
            ],
        ),
    ]
