# Generated by Django 3.1.1 on 2020-11-15 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences_role_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_level', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 12, 34, 24, 83880, tzinfo=utc), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 12, 34, 24, 83880, tzinfo=utc), null=True),
        ),
    ]
