# Generated by Django 3.1.1 on 2020-11-15 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_auto_20201115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 13, 28, 40, 17203, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 13, 28, 40, 17203, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(blank=True, max_length=150, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stat_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.countries')),
            ],
        ),
    ]
