# Generated by Django 3.1.1 on 2020-11-15 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_auto_20201115_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='countries',
            name='code',
        ),
        migrations.AddField(
            model_name='countries',
            name='capital',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='currncy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='emoji',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='emojiU',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='iso2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='iso3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='native',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='phone_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='subregion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 13, 58, 56, 815048, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 13, 58, 56, 815048, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.countries'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.countries'),
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.states'),
        ),
    ]
