# Generated by Django 3.1.1 on 2020-11-15 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_auto_20201115_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='currncy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='phone_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 14, 40, 28, 499134, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 14, 40, 28, 499134, tzinfo=utc), null=True),
        ),
    ]
