# Generated by Django 3.1.1 on 2020-11-15 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0013_auto_20201115_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 2, 49, 261872, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 2, 49, 261872, tzinfo=utc), null=True),
        ),
        migrations.RemoveField(
            model_name='states',
            name='country',
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.ManyToManyField(to='start.Countries'),
        ),
    ]
