# Generated by Django 3.1.1 on 2020-11-15 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0014_auto_20201115_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='country',
            new_name='country_id',
        ),
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 5, 6, 235727, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 5, 6, 235727, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='country_id',
            field=models.ManyToManyField(to='start.Countries'),
        ),
    ]
