# Generated by Django 3.1.1 on 2020-11-15 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0017_auto_20201115_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 14, 38, 694086, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 14, 38, 693083, tzinfo=utc), null=True),
        ),
    ]
