# Generated by Django 3.1.1 on 2020-11-15 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0019_auto_20201115_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 36, 5, 154464, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 15, 36, 5, 153358, tzinfo=utc), null=True),
        ),
    ]
