# Generated by Django 3.1.1 on 2020-11-15 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0020_auto_20201115_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='state_code',
        ),
        migrations.AlterField(
            model_name='experiences_role_level',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 16, 8, 43, 507342, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='job_type',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 15, 16, 8, 43, 506282, tzinfo=utc), null=True),
        ),
    ]
