# Generated by Django 3.1.1 on 2020-11-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0024_cities_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='visa_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='start.visa'),
        ),
    ]
