# Generated by Django 3.1.1 on 2020-11-17 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('start', '0025_auto_20201117_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('roles', models.TextField()),
                ('achievements', models.TextField()),
                ('description', models.TextField()),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.cities')),
                ('role_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.experiences_role_level')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.job_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
