# Generated by Django 3.1.1 on 2020-11-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0026_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='local_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.countries'),
        ),
    ]
