# Generated by Django 3.1.1 on 2020-11-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0030_educations_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educations',
            old_name='company',
            new_name='institute',
        ),
    ]
