# Generated by Django 3.1.1 on 2020-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0033_auto_20201118_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='lavel',
            new_name='level',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_logo',
            field=models.ImageField(default='skills_logo.png', upload_to='Skills'),
        ),
    ]
