# Generated by Django 3.1.1 on 2020-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0037_auto_20201122_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='current_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
