# Generated by Django 3.1.1 on 2020-11-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('start', '0038_user_profile_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('digits', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Js_job_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(blank=True, default='defultvideo.mp4', null=True, upload_to='Job_profile/{User.username}')),
                ('photo', models.ImageField(blank=True, default='showcase.jpg', null=True, upload_to='Job_profile/{User.username}')),
                ('is_activate', models.BooleanField(blank=True, default=False, null=True)),
                ('is_complated', models.BooleanField(blank=True, default=False, null=True)),
                ('likes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('views', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='start.currency')),
                ('targated_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='start.countries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visa_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='start.visa')),
            ],
        ),
        migrations.CreateModel(
            name='Job_profile_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.js_job_profile')),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Job_profile_show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.js_job_profile')),
                ('showcases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.showcase')),
            ],
        ),
        migrations.CreateModel(
            name='Job_profile_exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.experiences')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.js_job_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job_profile_endors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.references')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.js_job_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job_profile_edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.educations')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.js_job_profile')),
            ],
        ),
    ]
