# Generated by Django 3.1.1 on 2020-11-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0041_auto_20201123_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='js_job_profile',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='js_job_profile',
            name='shortlist',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
