# Generated by Django 3.1.1 on 2020-11-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0043_auto_20201123_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='js_job_profile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
