# Generated by Django 3.1.1 on 2020-11-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0044_auto_20201123_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
