# Generated by Django 3.1.1 on 2020-11-25 21:12

from django.db import migrations, models
import start.models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0046_auto_20201124_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('file', models.ImageField(blank=True, upload_to=start.models.upload_location)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
            },
        ),
    ]
