# Generated by Django 3.1.1 on 2020-11-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0047_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='image',
            new_name='file',
        ),
    ]
