# Generated by Django 3.1.1 on 2020-11-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0048_auto_20201126_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='file',
            new_name='image',
        ),
    ]
