from django.contrib import admin
from . import models  

admin.site.register(models.User_profile)
admin.site.register(models.Countries)
admin.site.register(models.States)
admin.site.register(models.Cities)
admin.site.register(models.Visa)
admin.site.register(models.Job_type)
admin.site.register(models.Experiences_role_level)
admin.site.register(models.Experiences)
admin.site.register(models.Educations)
admin.site.register(models.Skills)
admin.site.register(models.Showcase)
admin.site.register(models.References)
admin.site.register(models.Js_job_profile)
admin.site.register(models.Job_profile_edu)
admin.site.register(models.Job_profile_exp)
admin.site.register(models.Job_profile_show)
admin.site.register(models.Job_profile_skill)
admin.site.register(models.Job_profile_endors)
admin.site.register(models.Currency)
